# LDA - Linear Discriminant Analysis

## Step wise LDA

### Step 1 - Computing d-dimensional mean vectors

In [19]:
def kelas (file):
    if 'ha' in file: dot=1
    if 'na' in file: dot=2
    if 'ca' in file: dot=3
    if 'ra' in file: dot=4
    if 'ka' in file: dot=5
    if 'da' in file: dot=6
    if 'ta' in file: dot=7
    if 'sa' in file: dot=8
    if 'wa' in file: dot=9
    if 'la' in file: dot=10
    if 'ma' in file: dot=11
    if 'ga' in file: dot=12
    if 'ba' in file: dot=13
    if 'nga' in file: dot=14
    if 'pa' in file: dot=15
    if 'ja' in file: dot=16
    if 'ya' in file: dot=17
    if 'nya' in file: dot=18
    return dot
def norma (img):#normalisasi min max
    x,y = img.shape
    balik = np.zeros(img.shape)
    maks  = max(img.flatten())
    mins = min(img.flatten())
    for i in range(x):
        for j in range (y):
            balik[i,j]=(img[i,j]-mins)/(maks-mins)
    return balik.flatten()

In [20]:
import os
import numpy as np
import cv2
path = "G:\\datatestLDA"
i=0
ID = []
dt=np.zeros((900,32*32))
for r,d,f in os.walk(path):
    for file in f:
        img= cv2.imread(os.path.join(path,file),0)#grayscale
        x = cv2.resize(img,(32,32))#resize
        dt[i,:]= norma(x)
        print(norma(x))
        ID.append(kelas (file))
        i+=1
    print(dt.shape)

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1.

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1.

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1.

In [21]:
dt = np.array(dt)
ID = np.array(ID)
print(dt.shape, ID.shape)

print('data: ' + repr(dt),"\n")
print("ID :",ID,"\n")

(900, 1024) (900,)
data: array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]]) 

ID : [13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 13 13  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 

In [23]:
import sys
np.printoptions(threshold=sys.maxsize)

mean_vectors = []
for cl in range(1,19):
    mean_vectors.append(np.mean(dt[ID==cl], axis=0))
    print('Mean Vector class %s: %s\n' %(cl, mean_vectors[cl-1]))

Mean Vector class 1: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 2: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 3: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 4: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 5: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 6: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 7: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 8: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 9: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 10: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 11: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 12: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 13: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 14: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 15: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 16: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 17: [1. 1. 1. ... 1. 1. 1.]

Mean Vector class 18: [1. 1. 1. ... 1. 1. 1.]



### Step 2 - Computing the scatter matrices

#### 2.1 Within class scatter matrix

In [17]:
S_W = np.zeros((1024,1024))
for cl,mv in zip(range(1,19), mean_vectors):
    class_sc_mat = np.zeros((1024,1024))                  # scatter matrix for every class
    for row in dt[ID == cl]:
        row, mv = row.reshape(1024,1), mv.reshape(1024,1) # make column vectors
        class_sc_mat += (row-mv).dot((row-mv).T)
    S_W += class_sc_mat                             # sum class scatter matrices
print('within-class Scatter Matrix: \n', S_W)

within-class Scatter Matrix: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 2.2 Between class scatter matrix

In [18]:
overall_mean = np.mean(dt, axis=0)
overall_mean.shape
S_W.shape
np.linalg.det(S_W)

0.0

In [14]:
overall_mean = np.mean(dt, axis=0)

S_B = np.zeros((1024,1024))
for i,mean_vec in enumerate(mean_vectors):  #enumerate just adds a number from 0 to every value in object
    n = dt[y==i+1,:].shape[0]
    mean_vec = mean_vec.reshape(1024,1) # make column vector
    overall_mean = overall_mean.reshape(1024,1) # make column vector
    S_B += n * (mean_vec - overall_mean).dot((mean_vec - overall_mean).T)

print('between-class Scatter Matrix:\n', S_B)


NameError: name 'y' is not defined

In [ ]:
print(S_W.shape, S_B.shape)
for i in S_W:
    pass#print (i)

### Step 3 - Solving the generalized eigenvalue problem for the matrix S−1WSB

In [ ]:
print(np.linalg.pinv(S_W))
eig_vals, eig_vecs = np.linalg.eig(np.linalg.inv(S_W).dot(S_B)) #makes eigenvector from matrix

for i in range(len(eig_vals)):
    eigvec_sc = eig_vecs[:,i].reshape(1024,1)   
    print('\nEigenvector {}: \n{}'.format(i+1, eigvec_sc.real))
    print('Eigenvalue {:}: {:.2e}'.format(i+1, eig_vals[i].real))

In [ ]:
#Checking the eigenvector-eigenvalue calculation
for i in range(len(eig_vals)):
    eigv = eig_vecs[:,i].reshape(4,1)
    np.testing.assert_array_almost_equal(np.linalg.inv(S_W).dot(S_B).dot(eigv),
                                         eig_vals[i] * eigv,
                                         decimal=6, err_msg='', verbose=True)
print('ok')

#### 4.1 Ordering eigenvectors by decreasing order of eigenvalue

In [ ]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [ ]:
# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs = sorted(eig_pairs, key=lambda k: k[0], reverse=True)

In [ ]:
# Visually confirm that the list is correctly sorted by decreasing eigenvalues

print('Eigenvalues in decreasing order:\n')
for i in eig_pairs:
    print(i[0])

In [ ]:
#Representing values in %
print('Variance explained:\n')
eigv_sum = sum(eig_vals)
for i,j in enumerate(eig_pairs):
    print('eigenvalue {0:}: {1:.2%}'.format(i+1, (j[0]/eigv_sum).real))

#### 4.2 Choosing k eigenvectors with the largest eigenvalues

Here only 2 are adding information, hence selecting only first 2. We can also exclude the second one as the value add is too low.

In [ ]:
W = np.hstack((eig_pairs[0][1].reshape(4,1), eig_pairs[1][1].reshape(4,1))) #cbind 2 arrays
print('Matrix W:\n', W.real)

### Step 5 - Transforming the samples onto the new subspace

In [ ]:
X_lda = X.dot(W)
assert X_lda.shape == (150,2), "The matrix is not 150x2 dimensional." #Error debugger. If condition is true, does nothing, 
#else gives error message

In [ ]:
def plot_step_lda():

    ax = plt.subplot(111)
    for label,marker,color in zip(
        range(1,4),('^', 's', 'o'),('blue', 'red', 'green')):

        plt.scatter(x=X_lda[:,0].real[y == label],
                y=X_lda[:,1].real[y == label],
                marker=marker,
                color=color,
                alpha=0.5,
                label=label_dict[label]
                )

    plt.xlabel('LD1')
    plt.ylabel('LD2')

    leg = plt.legend(loc='upper right', fancybox=True)
    leg.get_frame().set_alpha(0.5)
    plt.title('LDA: Iris projection onto the first 2 linear discriminants')

    # hide axis ticks
    plt.tick_params(axis="both", which="both", bottom="off", top="off",  
            labelbottom="on", left="off", right="off", labelleft="on")

    # remove axis spines
    ax.spines["top"].set_visible(False)  
    ax.spines["right"].set_visible(False)
    ax.spines["bottom"].set_visible(False)
    ax.spines["left"].set_visible(False)    

    plt.grid()
    plt.tight_layout
    plt.show()

plot_step_lda()

## Comparison with PCA

In [ ]:
from sklearn.decomposition import PCA as sklearnPCA

sklearn_pca = sklearnPCA(n_components=2)
X_pca = sklearn_pca.fit_transform(X)

def plot_pca():

    ax = plt.subplot(111)

    for label,marker,color in zip(
        range(1,4),('^', 's', 'o'),('blue', 'red', 'green')):

        plt.scatter(x=X_pca[:,0][y == label],
                y=X_pca[:,1][y == label],
                marker=marker,
                color=color,
                alpha=0.5,
                label=label_dict[label]
                )

    plt.xlabel('PC1')
    plt.ylabel('PC2')

    leg = plt.legend(loc='upper right', fancybox=True)
    leg.get_frame().set_alpha(0.5)
    plt.title('PCA: Iris projection onto the first 2 principal components')

    # hide axis ticks
    plt.tick_params(axis="both", which="both", bottom="off", top="off",  
            labelbottom="on", left="off", right="off", labelleft="on")

    # remove axis spines
    ax.spines["top"].set_visible(False)  
    ax.spines["right"].set_visible(False)
    ax.spines["bottom"].set_visible(False)
    ax.spines["left"].set_visible(False)    

    plt.tight_layout
    plt.grid()

    plt.show()
plot_pca()
plot_step_lda()

## LDA Using scikit learn

In [ ]:
dt=[[0.0833,0.3333,0.6667,0.75,1,0.6667,0,0.25,0.5833],
    [0.125,0.8125,1,0.4375,0.4375,0.5625,0.125,0.1875,0],
    [0.2778,1,0.3333,0.5556,0.5556,0.3333,0.0556,0,0.7222],
    [0,1,0.2,0.0667,0,1,0.4667,0.2,0.2],
    [0.1111,1,0.3333,0.2222,0,0.8333,0.3889,0.8333,0.111],
    [0.3571,0.7143,0.4286,0.2857,0.0714,0.4286,0,0.3571,1],
    [0.2941,0.6471,0,0.0588,0.2941,1,1,0.1176,0.3529],
    [0.2308,0.7692,0,0.6923,0.3846,1,0.4615,0.8462,0.9231],
    [0.9333,0.6667,0,0.6,1,1,1,0.2,0.9333]]
ID = [1, 1, 1, 2, 2, 2, 3, 3, 3] 

In [ ]:
import numpy as np
dt = np.array(dt)
ID = np.array(ID)
print(X.shape, y.shape)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

# LDA
sklearn_lda = LDA(n_components=2)
X_lda_sklearn = sklearn_lda.fit_transform(X, y)

In [ ]:
def plot_scikit_lda(X, title):

    ax = plt.subplot(111)
    for label,marker,color in zip(
        range(1,4),('^', 's', 'o'),('blue', 'red', 'green')):

        plt.scatter(x=X[:,0][y == label],
                    y=X[:,1][y == label] * -1, # flip the figure
                    marker=marker,
                    color=color,
                    alpha=0.5,
                    label=label_dict[label])

    plt.xlabel('LD1')
    plt.ylabel('LD2')

    leg = plt.legend(loc='upper right', fancybox=True)
    leg.get_frame().set_alpha(0.5)
    plt.title(title)

    # hide axis ticks
    plt.tick_params(axis="both", which="both", bottom="off", top="off",  
            labelbottom="on", left="off", right="off", labelleft="on")

    # remove axis spines
    ax.spines["top"].set_visible(False)  
    ax.spines["right"].set_visible(False)
    ax.spines["bottom"].set_visible(False)
    ax.spines["left"].set_visible(False)    

    plt.grid()
    plt.tight_layout
    plt.show()

In [ ]:
plot_step_lda()
plot_scikit_lda(X_lda_sklearn, title='Default LDA via scikit-learn')